[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "aws.ses"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Vendor/Amazon", "Area/Marketing & Social Media", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.ses"
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
